### ISSUE TITLE
向邮箱地址发送邮件后，docker容器报错退出

### ISSUE THREAD

**Issue by xiaojiedev** [denghongcai/forsaken-mail#18]
基本信息：
CentOS7
Docker version 1.13.1, build 7d71120/1.13.1

报错内容：
```bash
[root@warma forsaken-mail]# docker logs cb5673affa92
> forsaken-mail@1.0.0 start
> node ./bin/www
warn: Python is not available. Dkim and spf checking is disabled.
warn: Either spamassassin or spamc are not available. Spam score computation is disabled.
info: Mailin Smtp server listening on port 25
(node:17) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
/forsaken-mail/node_modules/smtp-server/lib/smtp-stream.js:38
    this.closed = false;
                ^
TypeError: Cannot set property closed of #<Writable> which has only a getter
    at new SMTPStream (/forsaken-mail/node_modules/smtp-server/lib/smtp-stream.js:38:17)
    at new SMTPConnection (/forsaken-mail/node_modules/smtp-server/lib/smtp-connection.js:54:20)
    at SMTPServer.connect (/forsaken-mail/node_modules/smtp-server/lib/smtp-server.js:95:22)
    at SMTPServer.<anonymous> (/forsaken-mail/node_modules/smtp-server/lib/smtp-server.js:84:14)
    at Server.emit (node:events:514:28)
    at TCP.onconnection (node:net:2157:8)
Node.js v20.9.0
```

**Comment by xiaojiedev** [comment]
向邮箱地址发送的邮件为Xshell应用的注册邮件。

**Comment by bafflingbug** [comment]
尝试重新构建？

https://github.com/nodemailer/smtp-server/issues/197

**Comment by bafflingbug** [comment]
我通过将mailin包更换为node-mailin解决了相关问题。
```
"node-mailin": "npm:@umpacken/node-mailin@^2.6.1",
```
[修改方式参考](https://github.com/malaohu/forsaken-mail/commit/8fc65b7de6c3084be6885293be8783c32c295324)

**Comment by GitSarp** [comment]
> 我通过将mailin包更换为node-mailin解决了相关问题。
> 
> ```
> "node-mailin": "npm:@umpacken/node-mailin@^2.6.1",
> ```
> 
> [修改方式参考](https://github.com/malaohu/forsaken-mail/commit/8fc65b7de6c3084be6885293be8783c32c295324)

对我没用
